apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  name: db
  labels:
    io.kompose.service: db
spec:
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
      - image: "{{ .Values.image.db.repository }}:{{ .Values.image.db.tag }}"
        name: db
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
        - name: db-claim0
          mountPath: /var/lib/mysql
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
