apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: "{{ .Values.image.db.repository }}:{{ .Values.image.db.tag }}"
        name: db
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
        - name: db-claim0
          mountPath: /var/lib/mysql
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
